version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: costsplit
      POSTGRES_PASSWORD: costsplit
      POSTGRES_DB: costsplit

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'

volumes:
  postgres:
