"""add trip name length constraint

Revision ID: ba980a5a2423
Revises: 667e24338945
Create Date: 2021-12-20 22:36:12.263311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba980a5a2423'
down_revision = '667e24338945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
