"""add_participant

Revision ID: 88c03f5f9cb5
Revises: ba980a5a2423
Create Date: 2022-01-01 19:53:33.952946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c03f5f9cb5'
down_revision = 'ba980a5a2423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_participant_trip_id_trip'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant')),
    sa.UniqueConstraint('trip_id', 'user_id', name=op.f('uq_participant_trip_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###
