"""rename proportions to parts

Revision ID: 964ad909789b
Revises: a45ee114ea04
Create Date: 2022-01-12 20:57:08.517920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '964ad909789b'
down_revision = 'a45ee114ea04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'proportions', new_column_name='parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'parts', new_column_name='proportions')
    # ### end Alembic commands ###
