"""extract parts to table

Revision ID: 2307eb31e9ea
Revises: 964ad909789b
Create Date: 2022-01-22 17:42:39.661526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2307eb31e9ea'
down_revision = '964ad909789b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['debtor_id'], ['participant.id'], name=op.f('fk_part_debtor_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_part_expense_id_expense'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part'))
    )
    op.drop_column('expense', 'parts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_table('part')
    # ### end Alembic commands ###
